### ISSUE TITLE
Waffle.io - Admin API

### ISSUE THREAD

**Issue by tudor-rusu** [civictechro/DSU-reportapp-api-admin#3]
Lucian trebuie sa adauge in waffle.io si repo-ul de la Admin API in https://waffle.io/civictechro/DSU-reportapp-api
Daca nu este posibil ca Waffle sa accepte doua repo-uri pe board, atunci trebuie facut un board nou numai pentru Admin.

**Comment by lucianstuparu** [comment]
Already done. Cand adaugi un nou issue, poti selecta din 3 repo-uri assignate proiectului.
